generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Answer
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          answer
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [text, question]
      filter:
        class: false
      form:    ~
      edit:    ~
      new:     ~
