generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Question
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          question
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        discription: { label: "Description" }
      list:
        display: [text, discription, created_at]
      filter:
        class: false
      form:
      edit:
        display: [text, discription, multichoice, answers]
      new:
        display: [text, discription, multichoice]
